version: '3'
services:
  node:
    container_name: node
    image: parcel-react-sample
    volumes:
      - .:/app
    ports:
      - '1234:1234'
    working_dir: /app
    command: >
      bash -c 'cp -rp /tmp/src /app &&
      npm i &&
      echo "Start React + Parcel !!"'
    tty: true
